spring:
  datasource:
    url: jdbc:h2:mem:h2db
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  application:
    name: produto

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2

  jmx:
    enabled: false

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin


server:
  port: 8081
  servlet:
    context-path: /produto


produto:
  rabbitmq:
    exchange: produto.exchange
    routingkey: produto.routingkey
    queue: produto.queue

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka


