
CREATE TABLE tb_permissao (
	id INT GENERATED BY DEFAULT AS IDENTITY,
	descricao varchar(255) NOT NULL,
	CONSTRAINT permissao_pkey PRIMARY KEY (id)
);

CREATE TABLE tb_usuario (
	id INT GENERATED BY DEFAULT AS IDENTITY,
	user_name varchar(255) NOT NULL,
	password varchar(255) NOT NULL,
	account_non_expired BOOLEAN NOT NULL,
	account_non_locked BOOLEAN NOT NULL,
	credentials_non_expired BOOLEAN NOT NULL,
	enabled BOOLEAN NOT NULL,
	CONSTRAINT usuario_pkey PRIMARY KEY (id)
);

CREATE TABLE usuario_permissao (
	usuario_id INT NOT NULL,
	permissao_id INT NOT NULL,
    PRIMARY KEY (usuario_id, permissao_id),
    FOREIGN KEY (usuario_id) REFERENCES tb_usuario(id),
    FOREIGN KEY (permissao_id) REFERENCES tb_permissao(id)
);
